# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 650)
        MainWindow.setStyleSheet("\n"
"border: none;\n"
"border-color: rgb(255, 255, 255);\n"
"\n"
"QFrame{\n"
"    border:none;\n"
"    margin:0px;\n"
"}\n"
"QToolTip {\n"
"    color: #333;\n"
"    background-color: #f8f8f2;\n"
"    border: 1px solid #CCC;\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(self.centralwidget)
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/assets/assets/logo.svg"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.title_lbl = QtWidgets.QLabel(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_lbl.sizePolicy().hasHeightForWidth())
        self.title_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.horizontalLayout.addWidget(self.title_lbl, 0, QtCore.Qt.AlignLeft)
        self.exit_btn = QtWidgets.QPushButton(self.Header)
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background-color: transparent;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(235, 235, 235);\n"
"}")
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/assets/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(30, 30))
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.Body = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.Body)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"    border: 1px solid red;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.General)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.General)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rest_time = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rest_time.sizePolicy().hasHeightForWidth())
        self.rest_time.setSizePolicy(sizePolicy)
        self.rest_time.setMaximumSize(QtCore.QSize(16777215, 100))
        self.rest_time.setStyleSheet("border:none;")
        self.rest_time.setSmallDecimalPoint(False)
        self.rest_time.setDigitCount(9)
        self.rest_time.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.rest_time.setProperty("value", 100.0)
        self.rest_time.setObjectName("rest_time")
        self.verticalLayout_4.addWidget(self.rest_time)
        self.request_btn = QtWidgets.QPushButton(self.frame)
        self.request_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.request_btn.setStyleSheet(".QPushButton {    \n"
"    background-color: rgba(39,119,255,255);\n"
"    color: white;\n"
"    padding: 20px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    font-size:20px;\n"
"    margin: 0px;\n"
"}\n"
".QPushButton:hover {\n"
"    background-color: #3d85ff;\n"
"}\n"
".QPushButton:pressed {    \n"
"    background-color: #204a91;\n"
"    color:#878a91;\n"
"}")
        self.request_btn.setObjectName("request_btn")
        self.verticalLayout_4.addWidget(self.request_btn)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.General)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.tabWidget.addTab(self.General, "")
        self.auto_fetch = QtWidgets.QWidget()
        self.auto_fetch.setObjectName("auto_fetch")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.auto_fetch)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.auto_fetch)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_auto_fetch = AnimatedToggle(self.frame_5)
        self.checkBox_auto_fetch.setObjectName("checkBox_auto_fetch")
        self.gridLayout.addWidget(self.checkBox_auto_fetch, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.hours_value_label = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.hours_value_label.setFont(font)
        self.hours_value_label.setObjectName("hours_value_label")
        self.verticalLayout_7.addWidget(self.hours_value_label, 0, QtCore.Qt.AlignLeft)
        self.hours_slider = QtWidgets.QSlider(self.frame_7)
        self.hours_slider.setMaximum(23)
        self.hours_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hours_slider.setObjectName("hours_slider")
        self.verticalLayout_7.addWidget(self.hours_slider)
        self.gridLayout_2.addWidget(self.frame_7, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.minutes_value_label = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.minutes_value_label.setFont(font)
        self.minutes_value_label.setObjectName("minutes_value_label")
        self.verticalLayout_8.addWidget(self.minutes_value_label, 0, QtCore.Qt.AlignLeft)
        self.minutes_slider = QtWidgets.QSlider(self.frame_8)
        self.minutes_slider.setMinimum(1)
        self.minutes_slider.setMaximum(59)
        self.minutes_slider.setProperty("value", 15)
        self.minutes_slider.setOrientation(QtCore.Qt.Horizontal)
        self.minutes_slider.setObjectName("minutes_slider")
        self.verticalLayout_8.addWidget(self.minutes_slider)
        self.gridLayout_2.addWidget(self.frame_8, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.verticalLayout_5.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.auto_fetch)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_18.setSpacing(25)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_19 = QtWidgets.QFrame(self.frame_4)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_quote_auto_fetch = AnimatedToggle(self.frame_19)
        self.checkBox_quote_auto_fetch.setObjectName("checkBox_quote_auto_fetch")
        self.gridLayout_5.addWidget(self.checkBox_quote_auto_fetch, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_12 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout_18.addWidget(self.frame_19, 0, QtCore.Qt.AlignTop)
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setVerticalSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_quran_auto_fetch = AnimatedToggle(self.frame_20)
        self.checkBox_quran_auto_fetch.setObjectName("checkBox_quran_auto_fetch")
        self.gridLayout_6.addWidget(self.checkBox_quran_auto_fetch, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_14 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout_18.addWidget(self.frame_20, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.tabWidget.addTab(self.auto_fetch, "")
        self.wallpaper_source = QtWidgets.QWidget()
        self.wallpaper_source.setObjectName("wallpaper_source")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.wallpaper_source)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_9 = QtWidgets.QFrame(self.wallpaper_source)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_10)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background-color:  rgba(39,119,255,255);\n"
"    border-radius: 5px;\n"
"    border: 2px solid  rgba(39,119,255,255);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: white;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid #3d85ff;\n"
"    background-color: #3d85ff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: #3d85ff;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/assets/assets/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: #6272a4;\n"
"    padding: 10px;\n"
"    selection-background-color: #6272a4;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 2, 1, 1, 2)
        self.verticalLayout_10.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_11)
        self.stackedWidget.setObjectName("stackedWidget")
        self.unsplash_page = QtWidgets.QWidget()
        self.unsplash_page.setObjectName("unsplash_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.unsplash_page)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_12 = QtWidgets.QFrame(self.unsplash_page)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.unsplash_keyword_lineedit = QtWidgets.QLineEdit(self.frame_13)
        self.unsplash_keyword_lineedit.setStyleSheet("QLineEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"    padding: 5px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgba(39,119,255,255);\n"
"}")
        self.unsplash_keyword_lineedit.setObjectName("unsplash_keyword_lineedit")
        self.verticalLayout_14.addWidget(self.unsplash_keyword_lineedit)
        self.verticalLayout_13.addWidget(self.frame_13, 0, QtCore.Qt.AlignTop)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_featured_unsplash = AnimatedToggle(self.frame_16)
        self.checkBox_featured_unsplash.setObjectName("checkBox_featured_unsplash")
        self.gridLayout_4.addWidget(self.checkBox_featured_unsplash, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_9 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout_15.addWidget(self.frame_16)
        self.verticalLayout_13.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_13.addWidget(self.frame_15)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.unsplash_page)
        self.wallhaven_page = QtWidgets.QWidget()
        self.wallhaven_page.setObjectName("wallhaven_page")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.wallhaven_page)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_17 = QtWidgets.QFrame(self.wallhaven_page)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setGeometry(QtCore.QRect(0, 0, 440, 50))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_17.addWidget(self.label_11)
        self.wallhaven_keyword_lineedit = QtWidgets.QLineEdit(self.frame_18)
        self.wallhaven_keyword_lineedit.setStyleSheet("QLineEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"    padding: 5px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid  rgba(39,119,255,255);\n"
"}")
        self.wallhaven_keyword_lineedit.setObjectName("wallhaven_keyword_lineedit")
        self.verticalLayout_17.addWidget(self.wallhaven_keyword_lineedit)
        self.verticalLayout_16.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.wallhaven_page)
        self.verticalLayout_11.addWidget(self.stackedWidget)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.tabWidget.addTab(self.wallpaper_source, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.Body)
        self.Footer = QtWidgets.QFrame(self.centralwidget)
        self.Footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Footer.setObjectName("Footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.author = QtWidgets.QLabel(self.Footer)
        self.author.setObjectName("author")
        self.horizontalLayout_2.addWidget(self.author)
        self.version = QtWidgets.QLabel(self.Footer)
        self.version.setObjectName("version")
        self.horizontalLayout_2.addWidget(self.version, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.Footer, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_lbl.setText(_translate("MainWindow", "Random Wallpaper"))
        self.exit_btn.setToolTip(_translate("MainWindow", "Exit Random Wallpaper"))
        self.request_btn.setText(_translate("MainWindow", "Request New Wallpaper"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General), _translate("MainWindow", "General"))
        self.checkBox_auto_fetch.setText(_translate("MainWindow", "CheckBox"))
        self.label_3.setText(_translate("MainWindow", "Automatically fetch new wallpapers based on an interval."))
        self.label_2.setText(_translate("MainWindow", "Auto-Fetching"))
        self.label_4.setText(_translate("MainWindow", "Hours"))
        self.hours_value_label.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Minutes"))
        self.minutes_value_label.setText(_translate("MainWindow", "15"))
        self.checkBox_quote_auto_fetch.setText(_translate("MainWindow", "CheckBox"))
        self.label_12.setText(_translate("MainWindow", "Automatically fetch new daily quotes."))
        self.label_13.setText(_translate("MainWindow", "Quotes Auto-Fetch"))
        self.checkBox_quran_auto_fetch.setText(_translate("MainWindow", "CheckBox"))
        self.label_14.setText(_translate("MainWindow", "Automatically fetch an ayah from the Quran."))
        self.label_15.setText(_translate("MainWindow", "Quran Auto-Fetch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.auto_fetch), _translate("MainWindow", "Auto-Fetching"))
        self.label_6.setText(_translate("MainWindow", "Wallpaper Source"))
        self.label_7.setText(_translate("MainWindow", "The source that is used to fetch random wallpapers."))
        self.comboBox.setItemText(0, _translate("MainWindow", "Unsplash"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Wallhaven"))
        self.label_8.setText(_translate("MainWindow", "Keywords"))
        self.unsplash_keyword_lineedit.setPlaceholderText(_translate("MainWindow", "Keywords...(comma separated)"))
        self.checkBox_featured_unsplash.setText(_translate("MainWindow", "CheckBox"))
        self.label_9.setText(_translate("MainWindow", "This option results in a smaller wallpaper pool, but the images are \n"
"considered to be of higher quality."))
        self.label_10.setText(_translate("MainWindow", "Only Featured Images"))
        self.label_11.setText(_translate("MainWindow", "Keyword"))
        self.wallhaven_keyword_lineedit.setPlaceholderText(_translate("MainWindow", "Keywrods... (comma separated)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wallpaper_source), _translate("MainWindow", "Wallpaper Source"))
        self.author.setText(_translate("MainWindow", "By : Ayoub Nouri"))
        self.version.setText(_translate("MainWindow", "V0.1.0"))
from AnimatedToggle import AnimatedToggle
import resource_rc
